# ---- Build Stage ----
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG REACT_APP_API_URL=""
ARG REACT_APP_KAKAO_API_KEY
ARG REACT_APP_ACCOUNT_AUTH_API_URL
ARG REACT_APP_ACCOUNT_AUTH_KEY
ARG REACT_APP_PG_PAYMENT_API_URL
ARG REACT_APP_PG_AUTH_KEY
ARG REACT_APP_PG_AUTH_TMN_ID

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_KAKAO_API_KEY=$REACT_APP_KAKAO_API_KEY
ENV REACT_APP_ACCOUNT_AUTH_API_URL=$REACT_APP_ACCOUNT_AUTH_API_URL
ENV REACT_APP_ACCOUNT_AUTH_KEY=$REACT_APP_ACCOUNT_AUTH_KEY
ENV REACT_APP_PG_PAYMENT_API_URL=$REACT_APP_PG_PAYMENT_API_URL
ENV REACT_APP_PG_AUTH_KEY=$REACT_APP_PG_AUTH_KEY
ENV REACT_APP_PG_AUTH_TMN_ID=$REACT_APP_PG_AUTH_TMN_ID

RUN npm run build:dev

# ---- Serve Stage ----
FROM node:20-alpine
RUN npm install -g serve

COPY --from=build /app/build /app/build
COPY --from=build /app/.env.development ./.env.development

EXPOSE 6141
CMD ["serve", "-s", "/app/build", "-l", "6141"]
